// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace API02.Models;

[PrimaryKey("Dept_Id", "Crs_Id")]
[Table("DepartmentCourseAssignment")]
public partial class DepartmentCourseAssignment
{
    public int Dept_Id { get; set; }

    public int Crs_Id { get; set; }

    [ForeignKey("Dept_Id")]
    public virtual Department Dept { get; set; }

    [ForeignKey("Crs_Id")]
    public virtual Course Crs { get; set; }
}